### ISSUE TITLE
[Question] mask_img == 255

### ISSUE THREAD

**Issue by EadCat** [ar90n/poisson-blending-in-5lines#1]
Hi, Thank you for the nice implementation.

I have a question about your code, that is Line 26 of notebook.example.py
The source and the target are normalized by 255. But the mask becomes boolean [False, True].
I think this makes the difference as follows:
![vinci_result=bool](https://github.com/ar90n/poisson-blending-in-5lines/assets/59416168/ac3d8840-be3a-41e6-aede-478cf1729512)
[Boolean, mask_img == 255]
![vinci_result](https://github.com/ar90n/poisson-blending-in-5lines/assets/59416168/948839d4-c48d-4458-a616-3c16db940a4b)
[Float, mask_img / 255]

Can you explain this?
Just to stop the blur of the mask? Or is there any more reason?
Why did you set it as Boolean? On the surface, the boolean setting looks better.

**Comment by ar90n** [comment]
Hi @EadCat .
This mask image is not a binary image which means that it contains some pixels whose intensity is not 0 or 255.
So I used this equation to use this image as binary.

**Comment by EadCat** [comment]
Okay, so should the all pixels be binary? In other words, do non-binary pixel values always adversely affect Poisson blending?

**Comment by ar90n** [comment]
In my view, mask_img indicates the blending area and should be binary. However, I'm not certain about the effects of using a non-binary mask. It might have benefits for some cases.

**Comment by EadCat** [comment]
I see. Thank you for your answer. I'll think about it.
